#!/bin/bash

installing(){
	echo "Preparando instalación"
	pkg install php php-apache -y
}
folder(){
	dir=/data/data/com.termux/files/home/www
	mkdir $dir
	echo "<?php phpinfo();" > $dir/index.php
}

main(){
	installing
	folder
	echo "Instalación terminada"
}

main
